### ISSUE TITLE
Error: No instrument is found in the subscription file. Please check the file path and the content of the subscription file

### ISSUE THREAD

**Issue by sparcusa** [Aurora-Team/BitcoinExchangeFH#88]
disregard,   I figured it out

**Comment by lman** [comment]
@sparcusa hi! How did you solve this problem?

**Comment by gavincyi** [comment]
I think you can follow the following steps to diagnose it:

1. Input the full/absolute path rather than relative path first. For example, even though you think your file is in the local directory, try to put `--config /home/yourname/your/path/instruments.ini` first. If it works fine, then your path is incorrect.

2. If you have input your absolute path but still find the same error, please try to copy one instrument from the [sample file](https://github.com/Aurora-Team/BitcoinExchangeFH/blob/master/subscriptions.ini) into your one first.
